In [39]:
import struct
import numpy as np
fileName = '../LeNet-5/model.dat'
with open(fileName, mode='rb') as file: # b is important -> binary
    fileContent = file.read()

# print(len(fileContent))
# struct.unpack("dddd", fileContent[:32])
# All = struct.unpack("d" * (51902*8 // 8), fileContent[0:51902*8])

W0_1 = struct.unpack("d" * (150*8 // 8), fileContent[0:150*8])  # Layer 1 Weights: 150 weights, 8 bytes each (double type)
W2_3 = struct.unpack("d" * (2400*8 // 8), fileContent[0:2400*8])  # Layer 1 Weights: 150 weights, 8 bytes each (double type)
W4_5 = struct.unpack("d" * (48000*8 // 8), fileContent[0:48000*8])  # Layer 1 Weights: 150 weights, 8 bytes each (double type)
W5_6 = struct.unpack("d" * (1200*8 // 8), fileContent[0:1200*8])  # Layer 1 Weights: 150 weights, 8 bytes each (double type)
B0_1 = struct.unpack("d" * (6*8 // 8), fileContent[0:6*8])  # Layer 1 Weights: 150 weights, 8 bytes each (double type)
B2_3 = struct.unpack("d" * (16*8 // 8), fileContent[0:16*8])  # Layer 1 Weights: 150 weights, 8 bytes each (double type)
B4_5 = struct.unpack("d" * (120*8 // 8), fileContent[0:120*8])  # Layer 1 Weights: 150 weights, 8 bytes each (double type)
B5_6 = struct.unpack("d" * (10*8 // 8), fileContent[0:10*8])  # Layer 1 Weights: 150 weights, 8 bytes each (double type)

W4_5_arr = np.array(W4_5)
print(W4_5_arr[:30])
# W2 = struct.unpack("d" * (2400*8 // 8), fileContent[0:2400*8])  # Layer 1 Weights: 150 weights, 8 bytes each (double type)



[ 3.93971135e-01  4.67213025e-02 -1.80625084e-04  1.36307913e-02
 -2.21178388e-01 -6.18252363e-02 -3.32166795e-03 -3.90243731e-02
 -1.84858312e-01  3.08486989e-02  5.18828814e-02 -2.14620388e-01
  5.01195758e-02 -1.54016819e-01 -1.46817008e-01 -2.50610921e-01
  7.33023469e-05  7.41493470e-03 -1.01639564e-01 -5.72009779e-02
 -1.37021345e-01 -6.02213593e-02 -1.42841084e-01 -1.85295947e-01
  1.15635728e-01 -1.47791150e-01 -3.55640308e-02 -9.14762005e-02
 -4.83934556e-02 -1.77979256e-01]


In [41]:
W4_5_mat = W4_5_arr.reshape(16,120,5,5)
print(W4_5_mat[0,0,:,:])

[[ 3.93971135e-01  4.67213025e-02 -1.80625084e-04  1.36307913e-02
  -2.21178388e-01]
 [-6.18252363e-02 -3.32166795e-03 -3.90243731e-02 -1.84858312e-01
   3.08486989e-02]
 [ 5.18828814e-02 -2.14620388e-01  5.01195758e-02 -1.54016819e-01
  -1.46817008e-01]
 [-2.50610921e-01  7.33023469e-05  7.41493470e-03 -1.01639564e-01
  -5.72009779e-02]
 [-1.37021345e-01 -6.02213593e-02 -1.42841084e-01 -1.85295947e-01
   1.15635728e-01]]


In [117]:
W4_5_mat_reshape = np.transpose(W4_5_mat,axes=(3,2,0,1)) #target layer weights
u,d,vh = np.linalg.svd(W4_5_mat_reshape) #perform svd
print(W4_5_mat_reshape.shape) #print original shape
print(u.shape) #print u matrix dimensions
print(d.shape) #print d matrix dimentions
print(vh.shape)#print vh matrix dimensions

print(d) #print singular values

(5, 5, 16, 120)
(5, 5, 16, 16)
(5, 5, 16)
(5, 5, 120, 120)
[[[1.05340068 0.58906443 0.52836382 0.48240853 0.3898115  0.34734631
   0.33130012 0.31500824 0.29133183 0.28922337 0.26060991 0.25687336
   0.24048728 0.23936618 0.20848376 0.20568999]
  [1.02886895 0.67826112 0.50427543 0.4721664  0.43775122 0.37173894
   0.36118952 0.34730814 0.31803852 0.306117   0.28564052 0.26793229
   0.24966746 0.24636662 0.23652563 0.21758735]
  [1.05496664 0.72701675 0.64646182 0.54813123 0.48979313 0.45138966
   0.3798674  0.37036387 0.35767061 0.32005938 0.30387523 0.26950274
   0.26925691 0.24921979 0.22546377 0.20466496]
  [0.96313639 0.71916506 0.57892847 0.51288265 0.44227738 0.38045791
   0.37429098 0.32115888 0.30816639 0.292032   0.28878199 0.27427011
   0.27071421 0.23731098 0.22958853 0.22660038]
  [1.02184284 0.65685855 0.52158224 0.45050369 0.40555032 0.35777247
   0.32008592 0.30155567 0.2900693  0.2882266  0.27478223 0.2672323
   0.25695739 0.23556536 0.22371524 0.21064159]]

 [[0.97533

In [82]:
B = np.array(range(0,48))
BB = B.reshape(4,3,2,2)
print(B)
print(BB)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]


 [[[24 25]
   [26 27]]

  [[28 29]
   [30 31]]

  [[32 33]
   [34 35]]]


 [[[36 37]
   [38 39]]

  [[40 41]
   [42 43]]

  [[44 45]
   [46 47]]]]


In [114]:
print(np.transpose(BB,axes=(3,2,0,1)))

[[[[ 0  4  8]
   [12 16 20]
   [24 28 32]
   [36 40 44]]

  [[ 2  6 10]
   [14 18 22]
   [26 30 34]
   [38 42 46]]]


 [[[ 1  5  9]
   [13 17 21]
   [25 29 33]
   [37 41 45]]

  [[ 3  7 11]
   [15 19 23]
   [27 31 35]
   [39 43 47]]]]


In [103]:
maybe = np.reshape(B,(2,2,3,4),order='F') #fortran style indexing
print(maybe)

[[[[ 0 12 24 36]
   [ 4 16 28 40]
   [ 8 20 32 44]]

  [[ 2 14 26 38]
   [ 6 18 30 42]
   [10 22 34 46]]]


 [[[ 1 13 25 37]
   [ 5 17 29 41]
   [ 9 21 33 45]]

  [[ 3 15 27 39]
   [ 7 19 31 43]
   [11 23 35 47]]]]


In [111]:
print(np.transpose(maybe,axes=(0,1,3,2)))

[[[[ 0  4  8]
   [12 16 20]
   [24 28 32]
   [36 40 44]]

  [[ 2  6 10]
   [14 18 22]
   [26 30 34]
   [38 42 46]]]


 [[[ 1  5  9]
   [13 17 21]
   [25 29 33]
   [37 41 45]]

  [[ 3  7 11]
   [15 19 23]
   [27 31 35]
   [39 43 47]]]]
